language: python
python:
    - "2.7"

# command to install dependencies
install:
    - pip install pytest
    - pip install coveralls
    - pip install pytest-cov

# command to run tests
script:
    py.test --cov .

after_success:
    coveralls
